### ISSUE TITLE
메인 페이지 및 선생님 추천 시나리오

### ISSUE THREAD

**Issue by JacobKim0226** [hoon25/GrapIt#21]
# 메인 페이지 및 선생님 추천 시나리오

# 상세설명
* 홈페이지 메인 화면 구현
* 선생님 추천 화면 구현
* 진도체크 구현

# TODO
- [ ] 홈페이지 메인 화면 구현
- [ ] 선생님 추천 화면 구현
- [ ] 진도 체크 구현

# ETC 
기타사항 작성해주세요
