### ISSUE TITLE
WebSocket 서버 분리 및 Stomp 구조 변경

### ISSUE THREAD

**Issue by hoon25** [hoon25/GrapIt#23]
# WebSocket 서버 분리

# 상세설명
- SockJS + Stomp
- Front, Back

# TODO
- [ ] SockJs
- [ ] Stomp 구조 변경
- [ ] Front 코드 변경
- [ ] Back 코드 변경
- [ ] Back 테스트코드
- [ ] 통합 테스트코드

# ETC 
기타사항 작성해주세요
