### ISSUE TITLE
방 로직 변경

### ISSUE THREAD

**Issue by hoon25** [hoon25/GrapIt#86]
# 방 로직 변경

# 상세설명
방 생성/입장 시 비밀번호 입력
방에 인원이 없으면 자동 삭제
최대 3인 출입 가능
회원만 출입 가능

# TODO
- [ ] 방 생성/입장 시 비밀번호 입력
- [ ] 방에 인원이 없으면 자동 삭제
- [ ] 최대 3인 출입 가능
- [ ] 회원만 출입 가능

# ETC 
기타사항 작성해주세요
