### ISSUE TITLE
react css 버그 픽스

### ISSUE THREAD

**Issue by Byeong-soo** [hoon25/GrapIt#93]
# react css 버그 픽스

# 상세설명
- 2022.01.21.20:06 시점 로그 창에 뜨는 버그 픽스

# TODO
- [x] checksseion 오류
- [x] 방 리스트 보여줄때 키 미지정
- [x] <tr> 자식 컴포넌트 존재
- [x] <tbody> 안에 <div> 자식으로 존재

# ETC 
기타사항 작성해주세요
